# Generated by Django 4.2.6 on 2024-05-06 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100)),
                ("img", models.ImageField(upload_to="")),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=100)),
                ("content", models.TextField()),
                ("rank", models.FloatField()),
            ],
        ),
    ]
