# Generated by Django 4.2.6 on 2024-05-22 02:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_friend_date_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="date_created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="blog", name="description", field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="blog", name="markdown", field=models.TextField(default=""),
        ),
    ]
