# Generated by Django 4.2.6 on 2024-05-23 08:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_comment_date_created_alter_blog_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="date_published",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
