# Generated by Django 4.2.6 on 2024-05-27 02:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_notification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog", name="markdown", field=ckeditor.fields.RichTextField(),
        ),
    ]
